# .zshrc is for interactive shell configuration.
# You set options for the interactive shell there with the setopt and
# unsetopt commands. You can also load shell modules, set your history options,
# change your prompt, set up zle and completion, et cetera.
# You also set any variables that are only used in the interactive shell


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# virtualenvwrapper setup
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper_lazy.sh

# chruby setup
source /usr/local/opt/chruby/share/chruby/chruby.sh
# enable chruby autoswitching
source /usr/local/opt/chruby/share/chruby/auto.sh
# set default ruby
chruby 2.2.2

export TAG=`date +DEPLOYED-%F/%H%M`
export HISTSIZE=100000

alias arts="php artisan"
alias cda="composer dumpautoload"
alias pymanage="python manage.py"
daynote(){
 vim $(date +%Y-%m-%d).md
}

alias gaa="git add -A"
alias gst="git status"
alias gl="git pull"
alias gcm="git commit -m"
alias gam="git commit -am"
alias gd="git diff"
alias gs="git status"
unalias gb

alias ydl="noglob youtube-dl"
alias resetdns="dscacheutil -flushcache"
alias epoch="date +%s"
alias httpHere="python -m SimpleHTTPServer"

alias vi="vim"
alias vim="nvim"
alias tmx="tmux"
alias runs="reattach-to-user-namespace"

# Works shortcuts
alias ac-status="ssh ac-prod-1 'sudo supervisorctl status'"
alias gtd="git log --since="6am" --author='$GIT_AUTHOR' --oneline --no-merges | sed -e 's/^[a-z0-9]\{7\} //' | sed '/commit/d' | sed -e 's/^\([a-zA-Z0-9]\)/ - \1/' | tr -d '\n' | sed 's/\([a-zA-Z0-9]\)-\([a-zA-Z0-9]\)/\1_\2/' | tr '-' '\n' | sed -e '/^ $/d' | sed 's/^ /- /'"

# Git ignore generator
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

bindkey -e

# Automatically activate venv a `venv` directory is present on the current dir.
# Mostly used for tmux windows
if [ -d "venv" ] ; then
    source venv/bin/activate
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
