# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Virtualenv setup
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# chruby setup
source /usr/local/opt/chruby/share/chruby/chruby.sh
# enable chruby autoswitching
source /usr/local/opt/chruby/share/chruby/auto.sh

export PATH=/Applications/Postgres.app/Contents/Versions/9.3/bin:/Users/hndr/Tools/adt-bundle/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/php5/bin:/usr/local/go/bin:$PATH

export PATH=$PATH:$HOME/gocode/bin
export PATH=$PATH:$HOME/.composer/vendor/bin

export GIT_AUTHOR=Hendra
export HISTSIZE=1000

alias gtd="git log --since="6am" --author='$GIT_AUTHOR' --oneline --no-merges | sed -e 's/^[a-z0-9]\{7\} //' | sed '/commit/d' | sed -e 's/^\([a-zA-Z0-9]\)/ - \1/' | tr -d '\n' | sed 's/\([a-zA-Z0-9]\)-\([a-zA-Z0-9]\)/\1_\2/' | tr '-' '\n' | sed -e '/^ $/d' | sed 's/^ /- /'"

alias lsa='ls -lah'
alias ll='ls -l'
alias la='ls -lA'
alias sl=ls # often screw this up

alias arts="php artisan"
alias cda="composer dumpautoload"

alias gaa="git add -A"
alias gst="git status"
alias gl="git pull"
alias gcm="git commit -m"
alias gam="git commit -am"
alias gd="git diff"
alias gs="git status"

alias ydl="youtube-dl"
alias resetdns="dscacheutil -flushcache"
alias epoch="date +%s"

export CHEATPATH=~/.cheat
export CHEATCOLORS=true

# Weird python on OS X fix
export LC_ALL=en_US.UTF-8

# Git ignore generator
function gi() { curl http://www.gitignore.io/api/$@ ;}

bindkey -e
